spring:
  # Postgres Database
  datasource:
    url: jdbc:postgresql://localhost:5432
    username: root
    password: 1234
    driver-class-name: org.postgresql.Driver
  # JPA
  jpa:
    hibernate:
      ddl-auto: create # ???? ??? ?? (drop -> create)
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
